defaults: &defaults
    working_directory: ~/barrels-client
    docker:
        - image: circleci/node:8

version: 2
jobs:
    deploy:
        <<: *defaults
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: yarn install --production=false
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - persist_to_workspace:
                root: .
                paths:
                    - node_modules
            - run:
                name: Login to GitHub
                command: git config --global user.email $GH_EMAIL && git config --global user.name $GH_NAME
            - deploy:
                name: Deploy to GitHub Pages
                command: yarn deploy

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - deploy:
                filters:
                    branches:
                        only: master
